name: hulk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.6.5
  - hulk==0.0.2
  - pandas==0.23.4
  - seaborn==0.9.0
  - scikit-learn==0.19.2
  - simka==1.4.0
  - sra-tools==2.9.1_1
